code --install-extension albert.tabout
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chadalen.vscode-jetbrains-icon-theme
code --install-extension charliermarsh.ruff
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension fallenmax.mithril-emmet
code --install-extension formulahendry.code-runner
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension omthemes.omthemes
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension tamasfe.even-better-toml
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
