#!/usr/bin/env bash
# AUTO-GENERATED by scripts/gen-extension-installer.sh -- do not edit by hand.
# Source of truth: vscode/extensions.txt
# Regenerate: bash scripts/gen-extension-installer.sh vscode
set -e
BIN="code"
command -v "$BIN" >/dev/null 2>&1 || { echo "  $BIN not on PATH; skipping extensions." >&2; exit 0; }
while IFS= read -r ext; do
  case "$ext" in ""|\#*) continue ;; esac
  echo "  installing: $ext"
  "$BIN" --install-extension "$ext"
done < "$(dirname "$0")/extensions.txt"
