#!/usr/bin/env bash
# Generate an editor extension installer from an extensions.txt file.
#
#   scripts/gen-extension-installer.sh vscode   -> writes vscode/install_extensions.sh
#   scripts/gen-extension-installer.sh cursor   -> writes cursor/install_extensions.sh
#
# The extensions.txt file must live next to the target dir. The binary used
# to install falls back from `code` to `cursor` depending on the target so
# the generated script works whether the editor is on PATH or not.
#
# Regenerates the installer so the txt is the single source of truth and the
# installer can never drift from it (fixes the historical drift bug).
set -euo pipefail

dir="${1:?usage: $0 <vscode|cursor>}"
case "$dir" in
  vscode) bin="code"   ;;
  cursor) bin="cursor" ;;
  *) echo "unknown target: $dir" >&2; exit 2 ;;
esac

here="$(cd "$(dirname "$0")" && pwd)"
target_dir="$here/../$dir"
list="$target_dir/extensions.txt"
out="$target_dir/install_extensions.sh"

[ -f "$list" ] || { echo "missing $list" >&2; exit 1; }

{
  echo '#!/usr/bin/env bash'
  echo "# AUTO-GENERATED by scripts/gen-extension-installer.sh -- do not edit by hand."
  echo "# Source of truth: $dir/extensions.txt"
  echo "# Regenerate: bash scripts/gen-extension-installer.sh $dir"
  echo 'set -e'
  printf 'BIN="%s"\n' "$bin"
  echo 'command -v "$BIN" >/dev/null 2>&1 || { echo "  $BIN not on PATH; skipping extensions." >&2; exit 0; }'
  echo 'while IFS= read -r ext; do'
  echo '  case "$ext" in ""|\#*) continue ;; esac'
  echo '  echo "  installing: $ext"'
  echo '  "$BIN" --install-extension "$ext"'
  echo 'done < "$(dirname "$0")/extensions.txt"'
} > "$out"
chmod +x "$out"
echo "wrote $out"